"""initial migration

Revision ID: 10677e04381b
Revises: 
Create Date: 2026-06-19 12:45:25.141476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10677e04381b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canchas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=False),
    sa.Column('acceso', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('disponible', 'mantenimiento', 'inactiva')", name='ck_canchas_estado'),
    sa.CheckConstraint('precio >= 0', name='ck_canchas_precio_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rol IN ('deportista', 'dirigente', 'admin')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index('ix_notificaciones_usuario_leida', ['usuario_id', 'leida'], unique=False)

    op.create_table('ocupaciones_especiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('institucional', 'campeonato', 'mantenimiento')", name='ck_ocupaciones_tipo'),
    sa.CheckConstraint('hora_fin > hora_inicio', name='ck_ocupaciones_horas_validas'),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocupaciones_especiales', schema=None) as batch_op:
        batch_op.create_index('ix_ocupaciones_cancha_fecha', ['cancha_id', 'fecha'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('comprobante', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente_pago', 'validando', 'confirmada', 'cancelada')", name='ck_reservas_estado'),
    sa.CheckConstraint('monto >= 0', name='ck_reservas_monto_positivo'),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancha_id', 'fecha', 'hora', name='uq_reserva_cancha_fecha_hora')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index('ix_reservas_cancha_fecha', ['cancha_id', 'fecha'], unique=False)
        batch_op.create_index('ix_reservas_usuario_estado', ['usuario_id', 'estado'], unique=False)

    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado IN ('libre', 'ocupado', 'pendiente_pago', 'validando')", name='ck_horarios_estado'),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancha_id', 'hora', name='uq_horario_cancha_hora')
    )
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.create_index('ix_horarios_cancha_estado', ['cancha_id', 'estado'], unique=False)

    op.create_table('ordenes_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado_pago IN ('pendiente', 'validando', 'aprobado', 'rechazado')", name='ck_ordenes_pago_estado'),
    sa.CheckConstraint('monto >= 0', name='ck_ordenes_pago_monto_positivo'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('reserva_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_pago')
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_index('ix_horarios_cancha_estado')

    op.drop_table('horarios')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index('ix_reservas_usuario_estado')
        batch_op.drop_index('ix_reservas_cancha_fecha')

    op.drop_table('reservas')
    with op.batch_alter_table('ocupaciones_especiales', schema=None) as batch_op:
        batch_op.drop_index('ix_ocupaciones_cancha_fecha')

    op.drop_table('ocupaciones_especiales')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_notificaciones_usuario_leida')

    op.drop_table('notificaciones')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('canchas')
    # ### end Alembic commands ###
